-- Migration: Fix generation_jobs board_id type
-- SKIPPED: board_id should be UUID to match boards.id. Casting to TEXT is incorrect.
-- This migration previously attempted to change it to TEXT which caused FK violations.
